<a href="https://colab.research.google.com/github/Vickylk/TESTING/blob/main/Simple_Linear_Regression_Phase1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np # NumPy is a Python library used for working with arrays
import matplotlib.pyplot as plt # Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python


In [3]:
from google.colab import files # To upload files

In [4]:
import io # Python io module allows us to manage the file-related input and output operations.
import pandas as pd # pandas is a library used for working with data sets

In [5]:
data = files.upload() # using Data as a variable and uploading the csv file

Saving salary.csv to salary.csv


In [6]:
data # to view the file

{'salary.csv': b'\xef\xbb\xbfYears of Exp,Salary\r\n0,10000\r\n1,15000\r\n2,20000\r\n2.2,22000\r\n3,30000\r\n4,40000\r\n4.5,45000\r\n5,60000\r\n'}

In [8]:
df=pd.read_csv(io.StringIO(data['salary.csv'].decode('utf-8'))) # The StringIO module is an in-memory file-like object. This object can be used as input or output to the most function that would expect a standard file object

In [9]:
df.head # df.head shows all column

<bound method NDFrame.head of    Years of Exp  Salary
0           0.0   10000
1           1.0   15000
2           2.0   20000
3           2.2   22000
4           3.0   30000
5           4.0   40000
6           4.5   45000
7           5.0   60000>

In [11]:
independent=df[["Years of Exp"]]
independent  # independent input variable Years of exp

Years of Exp
0           0.0
1           1.0
2           2.0
3           2.2
4           3.0
5           4.0
6           4.5
7           5.0

In [12]:
dependent =df[["Salary"]]
dependent # dependent output variable salary

Salary
0   10000
1   15000
2   20000
3   22000
4   30000
5   40000
6   45000
7   60000

In [13]:
from sklearn.model_selection import train_test_split  # spliting training set and test set

In [18]:
train_test_split(independent,dependent,test_size=0.30,random_state=0)  # Both input and output variable test 70:30
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0) # X input train and test Y output train and test set

In [21]:
from sklearn.linear_model import LinearRegression # creating model using linear regression
regressor=LinearRegression() # regressor is a variable LinearRegression() is a class
regressor.fit(X_train,y_train) # regressor.fit calling the input and output values

LinearRegression()

In [23]:
weight=regressor.coef_  # to finding  the weight
weight

array([[9531.42227122]])

In [24]:
bais=regressor.intercept_ # To finding the bais
bais

array([5330.76074972])

In [25]:
y_pred=regressor.predict(X_test) # y_pred is a variable regressor.predict is to predict X test

In [26]:
from sklearn.metrics import r2_score # To find r score value
r_score=r2_score(y_test,y_pred) # y_test Actual output y_pred predicted value

In [27]:
r_score

0.9425062923202577

In [28]:
import pickle # pickle is a library to save the model
filename="finalized_model_linear.sav"

In [29]:
pickle.dump(regressor,open(filename,'wb')) # pickle.dump to store the file

In [30]:
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb')) # Loading the saved file

In [31]:
result=loaded_model.predict([[10]]) # result is variable calling the prediction

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [32]:
result

array([[100644.98346196]])