<a href="https://colab.research.google.com/github/Vickylk/TESTING/blob/main/upload_files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
from google.colab import files

In [8]:
import io

In [9]:
import pandas as pd

In [10]:
data = files.upload()

Saving salary.csv to salary.csv


In [11]:
data

{'salary.csv': b'\xef\xbb\xbfYears of Exp,Salary\r\n0,10000\r\n1,15000\r\n2,20000\r\n2.2,22000\r\n3,30000\r\n4,40000\r\n4.5,45000\r\n5,60000\r\n'}

In [12]:
df=pd.read_csv(io.StringIO(data['salary.csv'].decode('utf-8')))

In [13]:
df.head

<bound method NDFrame.head of    Years of Exp  Salary
0           0.0   10000
1           1.0   15000
2           2.0   20000
3           2.2   22000
4           3.0   30000
5           4.0   40000
6           4.5   45000
7           5.0   60000>

In [14]:
independent=df[["Years of Exp"]]

In [15]:
independent

Years of Exp
0           0.0
1           1.0
2           2.0
3           2.2
4           3.0
5           4.0
6           4.5
7           5.0

In [16]:
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
import io
import pandas as pd

data=files.upload()

Saving salary.csv to salary (1).csv


In [17]:
data

{'salary.csv': b'\xef\xbb\xbfYears of Exp,Salary\r\n0,10000\r\n1,15000\r\n2,20000\r\n2.2,22000\r\n3,30000\r\n4,40000\r\n4.5,45000\r\n5,60000\r\n'}

In [18]:
df=pd.read_csv(io.StringIO(data['salary.csv'].decode('utf-8')))

In [19]:
df

Years of Exp  Salary
0           0.0   10000
1           1.0   15000
2           2.0   20000
3           2.2   22000
4           3.0   30000
5           4.0   40000
6           4.5   45000
7           5.0   60000

In [20]:
df.head

<bound method NDFrame.head of    Years of Exp  Salary
0           0.0   10000
1           1.0   15000
2           2.0   20000
3           2.2   22000
4           3.0   30000
5           4.0   40000
6           4.5   45000
7           5.0   60000>

In [21]:
independent = df[["Years of Exp"]]

In [22]:
independent

Years of Exp
0           0.0
1           1.0
2           2.0
3           2.2
4           3.0
5           4.0
6           4.5
7           5.0

In [23]:
dependent =df[["Salary"]]

In [24]:
dependent

Salary
0   10000
1   15000
2   20000
3   22000
4   30000
5   40000
6   45000
7   60000

In [25]:
from sklearn.model_selection import train_test_split

In [30]:
train_test_split(independent,dependent,test_size=0.30,random_state=0)
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [31]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [32]:
weight=regressor.coef_

In [33]:
weight

array([[9531.42227122]])

In [34]:
bais=regressor.intercept_

In [35]:
bais

array([5330.76074972])

In [36]:
y_pred=regressor.predict(X_test)

In [37]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [38]:
r_score

0.9425062923202577

In [39]:
import pickle
filename="finalized_model_linear.sav"

In [40]:
pickle.dump(regressor,open(filename,'wb'))

In [41]:
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb'))

In [45]:
result=loaded_model.predict([[10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [46]:
result

array([[100644.98346196]])